version: '3.8'

services:
  gemini-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=True
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  redis-data: